import { useState, useCallback, useEffect } from "react";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";
import { depositDOI, generateDOIString } from "@/lib/crossref";
import {
  listManuscriptsFromDb,
  updateManuscriptRow,
  getManuscriptByIdFromDb,
} from "@/lib/manuscripts-db";
import { useAuth } from "@/contexts/AuthContext";
import type { Manuscript, ManuscriptStatus, ReadinessStatus } from "../types";
import { appendAudit, appendNotification } from "@/lib/workflow";

export interface UseManuscriptsOptions {
  filterStatus?: ManuscriptStatus;
  /** When true, only load post-acceptance pipeline rows (publication dashboard). */
  publicationOnly?: boolean;
}

export function useManuscripts(options?: UseManuscriptsOptions) {
  const filterStatus = options?.filterStatus;
  const publicationOnly = options?.publicationOnly ?? false;
  const { user, role } = useAuth();
  const [manuscripts, setManuscripts] = useState<Manuscript[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchManuscripts = useCallback(async () => {
    if (!user || !role) return;

    setLoading(true);
    setError(null);

    const { data, error: fetchError } = await listManuscriptsFromDb({
      userId: user.id,
      role,
      status: filterStatus,
      publicationStatusesOnly: publicationOnly,
    });

    if (fetchError) {
      setError(fetchError.message);
      toast.error(`Failed to fetch manuscripts: ${fetchError.message}`);
      setManuscripts([]);
    } else {
      setManuscripts(data);
    }

    setLoading(false);
  }, [filterStatus, publicationOnly, user?.id, role]);

  useEffect(() => {
    fetchManuscripts();
  }, [fetchManuscripts]);

  const getById = useCallback(async (id: string): Promise<Manuscript | null> => {
    const { data, error: fetchError } = await getManuscriptByIdFromDb(id);
    if (fetchError || !data) return null;
    return data;
  }, []);

  const getReadinessStatus = useCallback(
    (manuscript: Manuscript): ReadinessStatus => {
      const hasMetadata =
        !!manuscript.title &&
        manuscript.authors.length > 0 &&
        manuscript.keywords.length > 0;
      const hasFile = !!manuscript.file_url;
      const hasDOI = !!manuscript.doi;

      return {
        metadataComplete: hasMetadata,
        filesReady: hasFile,
        doiAssigned: hasDOI,
        isReady: hasMetadata && hasFile && hasDOI,
      };
    },
    []
  );

  const updateManuscript = useCallback(
    async (id: string, updates: Partial<Manuscript>): Promise<boolean> => {
      const payload: Record<string, unknown> = { ...updates };
      if (payload.submission_metadata && typeof payload.submission_metadata === "object") {
        payload.submission_metadata = payload.submission_metadata as Record<string, unknown>;
      }

      const { error: updateError } = await updateManuscriptRow(id, payload);

      if (updateError) {
        toast.error(`Update failed: ${updateError.message}`);
        return false;
      }

      setManuscripts((prev) =>
        prev.map((m) => (m.id === id ? { ...m, ...updates } : m))
      );
      return true;
    },
    []
  );

  const saveMetadata = useCallback(
    async (
      id: string,
      data: { title: string; authors: string[]; abstract: string; keywords: string[] }
    ) => {
      const success = await updateManuscript(id, data);
      if (success) toast.success("Metadata updated successfully");
      return success;
    },
    [updateManuscript]
  );

  const uploadFile = useCallback(
    async (id: string, file: File): Promise<boolean> => {
      const filePath = `manuscripts/${id}/${file.name}`;

      const { error: uploadError } = await supabase.storage
        .from("manuscript-files")
        .upload(filePath, file, { upsert: true });

      if (uploadError) {
        toast.error(`Upload failed: ${uploadError.message}`);
        return false;
      }

      const { data: urlData } = supabase.storage
        .from("manuscript-files")
        .getPublicUrl(filePath);

      const success = await updateManuscript(id, {
        file_url: urlData.publicUrl,
      });

      if (success) toast.success("File uploaded successfully");
      return success;
    },
    [updateManuscript]
  );

  const assignDOI = useCallback(
    async (id: string, doi: string) => {
      const success = await updateManuscript(id, { doi });
      if (success) toast.success("DOI assigned successfully");
      return success;
    },
    [updateManuscript]
  );

  const autoGenerateDOI = useCallback(
    async (
      id: string
    ): Promise<{ success: boolean; doi: string; error?: string }> => {
      const manuscript = manuscripts.find((m) => m.id === id);
      if (!manuscript) {
        const fresh = await getById(id);
        if (!fresh) return { success: false, doi: "", error: "Manuscript not found" };

        const result = await depositDOI(fresh);
        if (result.success) {
          await updateManuscript(id, { doi: result.doi });
        }
        return result;
      }

      const result = await depositDOI(manuscript);
      if (result.success) {
        await updateManuscript(id, { doi: result.doi });
      } else {
        const fallbackDOI = generateDOIString(manuscript);
        return { ...result, doi: fallbackDOI };
      }
      return result;
    },
    [manuscripts, getById, updateManuscript]
  );

  const publishManuscript = useCallback(
    async (id: string): Promise<boolean> => {
      const manuscript = manuscripts.find((m) => m.id === id);
      if (!manuscript) return false;

      const readiness = getReadinessStatus(manuscript);
      if (!readiness.isReady) {
        toast.error(
          "Cannot publish: Please complete all readiness requirements"
        );
        return false;
      }

      const updates: Partial<Manuscript> = {
        status: "Published",
        published_at: new Date().toISOString(),
        submission_metadata: {
          ...(manuscript.submission_metadata ?? {}),
          notifications: appendNotification(manuscript, {
            type: "published",
            recipientRole: "public",
            message: `${manuscript.reference_code ?? manuscript.id} is now published.`,
          }),
          audit_logs: appendAudit(manuscript, "production_editor", "published"),
        },
      };

      const success = await updateManuscript(id, updates);
      if (!success) return false;

      const { error: metricsError } = await supabase
        .from("article_metrics")
        .insert([
          { manuscript_id: id, views: 0, downloads: 0, citations: 0 },
        ]);

      if (metricsError) {
        console.error("Failed to create metrics row:", metricsError);
      }

      toast.success("Article successfully published!");
      return true;
    },
    [manuscripts, getReadinessStatus, updateManuscript]
  );

  const returnToRevision = useCallback(
    async (id: string) => {
      const manuscript = manuscripts.find((m) => m.id === id);
      const reference = manuscript?.reference_code ?? manuscript?.id ?? id;
      const success = await updateManuscript(id, {
        status: "Revision Requested" as ManuscriptStatus,
        submission_metadata: {
          ...(manuscript?.submission_metadata ?? {}),
          notifications: appendNotification(manuscript ?? ({} as Manuscript), {
            type: "revision-requested",
            recipientRole: "author",
            message: `${reference} was returned by production for revision.`,
          }),
          audit_logs: appendAudit(
            manuscript ?? ({} as Manuscript),
            "production_editor",
            "returned-to-revision"
          ),
        },
      });
      if (success) toast.success("Manuscript returned to author for revision");
      return success;
    },
    [manuscripts, updateManuscript]
  );

  const retractManuscript = useCallback(
    async (id: string) => {
      const success = await updateManuscript(id, {
        status: "Retracted" as ManuscriptStatus,
        submission_metadata: {
          ...(manuscripts.find((m) => m.id === id)?.submission_metadata ?? {}),
          audit_logs: appendAudit(
            manuscripts.find((m) => m.id === id) ?? ({} as Manuscript),
            "production_editor",
            "retracted"
          ),
        },
      });
      if (success) toast.error("Article has been retracted");
      return success;
    },
    [updateManuscript]
  );

  const assignIssue = useCallback(
    async (id: string, issueAssignment: string) => {
      const success = await updateManuscript(id, {
        issue_assignment: issueAssignment,
      } as Partial<Manuscript>);
      if (success) toast.success("Issue assignment saved");
      return success;
    },
    [updateManuscript]
  );

  const incrementDownload = useCallback(async (manuscriptId: string) => {
    const { data: current } = await supabase
      .from("article_metrics")
      .select("downloads")
      .eq("manuscript_id", manuscriptId)
      .single();

    if (current) {
      await supabase
        .from("article_metrics")
        .update({ downloads: (current.downloads || 0) + 1 })
        .eq("manuscript_id", manuscriptId);
    }
  }, []);

  const refreshMetrics = useCallback(async (id: string) => {
    const { data } = await supabase
      .from("article_metrics")
      .select("*")
      .eq("manuscript_id", id)
      .single();

    if (data) {
      setManuscripts((prev) =>
        prev.map((m) => (m.id === id ? { ...m, metrics: data } : m))
      );
      toast.success("Metrics refreshed");
    }
  }, []);

  return {
    manuscripts,
    loading,
    error,
    fetchManuscripts,
    getById,
    getReadinessStatus,
    updateManuscript,
    saveMetadata,
    uploadFile,
    assignDOI,
    autoGenerateDOI,
    publishManuscript,
    returnToRevision,
    retractManuscript,
    assignIssue,
    incrementDownload,
    refreshMetrics,
  };
}
